# Generated by Django 2.2.4 on 2020-12-23 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecomm', '0002_auto_20201222_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(
                decimal_places=2, default="19.99", max_digits=9),
            preserve_default=False,
        ),
    ]
